EVENT_CONTACT_NEW = "CONTACT_NEW"
EVENT_CONTACT_UPDATE = "CONTACT_UPDATE"
EVENT_CONTACT_LOST = "CONTACT_LOST"
EVENT_TELEMETRY_UPDATE = "TELEMETRY_UPDATE"
EVENT_REPLAY_STATE = "REPLAY_STATE"

CONTACT_TYPE_REMOTE_ID = "REMOTE_ID"

EVENT_TYPES = {
    EVENT_CONTACT_NEW,
    EVENT_CONTACT_UPDATE,
    EVENT_CONTACT_LOST,
    EVENT_TELEMETRY_UPDATE,
    EVENT_REPLAY_STATE,
}
